[package]
name = "rs-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "0.17.0", default-features = false }
serde_json = "1.0"
lambda_runtime = "0.14.0"
tokio = { version = "1", features = ["macros"] }
